apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-generator
  labels:
    app: poc-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-generator
  template:
    metadata:
      labels:
        app: poc-generator
    spec:
      containers:
      - name: poc-generator
        image: privaterepo.io/poc/poc-generator:0.4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /app/configuration
          name: config
        - mountPath: /app/configuration-mw
          name: config-mw
      volumes:
      - name: config
        configMap:
          name: poc-generator-configuration
          items:
          - key: "appconfig.yaml"
            path: appconfig.yaml
      - name: config-mw
        configMap:
          name: poc-generator-configuration-mw
          items:
          - key: "infraconfig.yaml"
            path: infraconfig.yaml