resources:
- ./../../../../../../apps/poc-app/1.0

namespace: poc-app-ns

configMapGenerator:

- name: poc-processor-configuration
  behavior: merge
  literals:
  - eventhub.name="poctest"
  - storage.containername="pocmessages"

